//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FerreteriaEntities : DbContext
    {
        public FerreteriaEntities()
            : base("name=FerreteriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pedido_cliente> pedido_cliente { get; set; }
        public virtual DbSet<pedido_cliente_producto> pedido_cliente_producto { get; set; }
        public virtual DbSet<pedido_cliente_servicio> pedido_cliente_servicio { get; set; }
        public virtual DbSet<pedido_completo> pedido_completo { get; set; }
        public virtual DbSet<pedido_completo_producto> pedido_completo_producto { get; set; }
        public virtual DbSet<pedido_completo_servicio> pedido_completo_servicio { get; set; }
        public virtual DbSet<pedido_solo_servicio> pedido_solo_servicio { get; set; }
        public virtual DbSet<pedido_solo_servicio_servicio> pedido_solo_servicio_servicio { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<transporte> transporte { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
