//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_solo_servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedido_solo_servicio()
        {
            this.pedido_solo_servicio_servicio = new HashSet<pedido_solo_servicio_servicio>();
        }
    
        public int id { get; set; }
        public string cedula_cliente { get; set; }
        public string codigo_constructor { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> hora_recibido_bodega { get; set; }
        public Nullable<System.DateTime> hora_salida_bodega { get; set; }
        public string codigo_conductor { get; set; }
        public Nullable<System.DateTime> hora_inicia_transporte { get; set; }
        public Nullable<System.DateTime> hora_finaliza_transporte { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public string codigo_cajero { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_solo_servicio_servicio> pedido_solo_servicio_servicio { get; set; }
    }
}
