//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_completo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedido_completo()
        {
            this.pedido_completo_producto = new HashSet<pedido_completo_producto>();
            this.pedido_completo_servicio = new HashSet<pedido_completo_servicio>();
        }
    
        public int id { get; set; }
        public string codigo_vendedor { get; set; }
        public string cedula_cliente { get; set; }
        public Nullable<System.DateTime> hora_atencion { get; set; }
        public Nullable<System.DateTime> hora_venta { get; set; }
        public Nullable<System.DateTime> hora_recibido_bodega { get; set; }
        public Nullable<System.DateTime> hora_salida_bodega { get; set; }
        public string codigo_conductor { get; set; }
        public Nullable<System.DateTime> hora_inicia_transporte { get; set; }
        public Nullable<System.DateTime> hora_finaliza_transporte { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public string codigo_cajero { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_completo_producto> pedido_completo_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_completo_servicio> pedido_completo_servicio { get; set; }
    }
}
