//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_completo_producto
    {
        public int id { get; set; }
        public int id_pedido_completo { get; set; }
        public int id_producto { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio_total { get; set; }
    
        public virtual pedido_completo pedido_completo { get; set; }
        public virtual producto producto { get; set; }
    }
}
