//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_completo_servicio
    {
        public int id { get; set; }
        public int id_pedido_completo { get; set; }
        public int id_servicio { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio_total { get; set; }
    
        public virtual pedido_completo pedido_completo { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
