//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class transporte
    {
        public int id { get; set; }
        public string numero_vehiculo { get; set; }
        public string codigo_conductor { get; set; }
        public bool disponible { get; set; }
        public bool activo { get; set; }
    }
}
