//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_spedido_cliente_servicio
    {
        public int id { get; set; }
        public int id_pedido_cliente { get; set; }
        public int id_servicio { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio_total { get; set; }
    }
}
